# Generated by Django 6.0.6 on 2026-06-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('data_prova', models.DateField()),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('estudo_concluido', models.BooleanField(default=False)),
            ],
        ),
    ]
