# Generated by Django 6.0.6 on 2026-06-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0003_avaliacao_usuario_disciplina_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='dificuldade',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='horas_ciclo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='horas_concluidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='peso',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='quantidade_conteudo',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
