# Generated by Django 6.0.6 on 2026-06-17 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudos', '0004_disciplina_dificuldade_disciplina_horas_ciclo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_registro', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteudos', to='estudos.disciplina')),
            ],
            options={
                'ordering': ['-data_registro', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='conteudos_cobrados',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes', to='estudos.conteudoaula'),
        ),
    ]
